name: Environment variables
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
    steps:
      - name: Check variable
        run: echo "The branch is ${{ env.BRANCH }}"
        run: echo "The Branch is "${BRANCH}"
      - name: CHeckout
        uses: actions/checkout@v5
        with:
          ref: ${{ env.BRANCH }}
